kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-github
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  username: YmVuc2Nod2FyejE5ODI=
  password: Z2hwX291S3VOYXJUUXdmWFFxZGlXQ0Q5VnFDQjJtZFRFdDJmNmRTVw==
type: kubernetes.io/basic-auth
---
kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-generic-webhook-secret
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  WebHookSecretKey: OWViNjE3OTU1ZjgwMDU1MQ==
type: Opaque