kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: html-openshift-app
  annotations:
    openshift.io/display-name: "html-openshift-app (Auftrag 6.2)"
    description: "A simple HTML Page"
    iconClass: "icon-play"
    tags: "html"

parameters:
  - name: NAMESPACE
    description: "Set Namespace as Variable"
    required: true
  - name: GIT_SOURCE_URI
    description: The URI to the GIT source for your application
    value: https://github.com/benschwarz1982/html-openshift-app.git
    required: true
  - name: GIT_USERNAME
    description: The Username of your GIT Account 
    required: true
  - name: GIT_PAT
    description: The Personal Access Token (PAT) of your GIT Account
    required: true

objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: html-openshift-app-github
      labels:
        app: html-openshift-app
        app.kubernetes.io/part-of: html-openshift-app
      annotations:
        template.openshift.io/expose-username: "${GIT_USERNAME}"
        template.openshift.io/expose-passsword: "${GIT_PAT}"      
    stringData:
      username: "${GIT_USERNAME}"
      password: "${GIT_PAT}"
    type: kubernetes.io/basic-auth

  - kind: Secret
    apiVersion: v1
    metadata:
      name: html-openshift-app-generic-webhook-secret
      labels:
        app: html-openshift-app
        app.kubernetes.io/part-of: html-openshift-app
    data:
      WebHookSecretKey: OWViNjE3OTU1ZjgwMDU1MQ==
    type: Opaque

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: html-openshift-app
      labels:
        app: html-openshift-app
        app.kubernetes.io/part-of: html-openshift-app
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: html-openshift-app
      template:
        metadata:
          labels:
            app: html-openshift-app
        spec:
          containers:
            - name: html-openshift-app
              resources: {}
              ports:
                - containerPort: 8080
                  protocol: TCP
              image: 'image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/html-openshift-app:latest'
              imagePullPolicy: Always
              
  - kind: Service
    apiVersion: v1
    metadata:
      name: html-openshift-app
      labels:
        app: html-openshift-app
        app.kubernetes.io/part-of: html-openshift-app
    spec:
      ports:
        - name: html-openshift-app
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: html-openshift-app

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: html-openshift-app
      labels:
        app: html-openshift-app
        app.kubernetes.io/part-of: html-openshift-app
    spec:
      to:
        kind: Service
        name: html-openshift-app
      port:
        targetPort: html-openshift-app
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
  
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: html-openshift-app
      labels:
        app: html-openshift-app
        app.kubernetes.io/part-of: html-openshift-app
    spec:

  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: html-openshift-app
      labels:
        app: html-openshift-app
        app.kubernetes.io/part-of: html-openshift-app
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'html-openshift-app:latest'
      resources: {}
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: 'nginx:1.20-ubi7'
      postCommit: {}
      source:
        type: Git
        git:
          uri: ${GIT_SOURCE_URI}
        contextDir: /app/web
        sourceSecret:
          name: html-openshift-app-github
      triggers:
        - type: Generic
          generic:
            secretReference:
              name: html-openshift-app-generic-webhook-secret
        - type: ImageChange
        - type: ConfigChange
      runPolicy: Serial